# Generated by Django 5.0.7 on 2024-08-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot_app', '0003_withdrawmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='eth_contribution',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='sol_contribution',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
