# Generated by Django 5.0.7 on 2024-07-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot_app', '0003_memonic_tokenlist_user_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mnemonic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_mnemonic',
            },
        ),
        migrations.DeleteModel(
            name='Memonic',
        ),
    ]
