# Generated by Django 5.0.7 on 2024-08-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot_app', '0004_usermodel_eth_contribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(max_length=100)),
                ('token_address', models.CharField(max_length=255)),
                ('token_amount', models.FloatField(default=0)),
                ('chain_type', models.CharField(max_length=10)),
                ('out_native_amount', models.FloatField()),
                ('out_gas_fee', models.FloatField()),
                ('in_native_amount', models.FloatField(default=0)),
                ('in_gas_fee', models.FloatField(default=0)),
                ('buy_sell_status', models.IntegerField(default=True)),
                ('buy_tx', models.CharField(max_length=255)),
                ('sell_tx', models.CharField(blank=True, max_length=255, null=True)),
                ('buy_at', models.DateTimeField(auto_now_add=True)),
                ('sell_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tbl_trade',
            },
        ),
    ]
