# Generated by Django 5.0.7 on 2024-08-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot_app', '0005_trademodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='user_contribution',
            field=models.TextField(default=''),
        ),
    ]
