# Generated by Django 5.0.7 on 2024-09-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot_app', '0006_trademodel_user_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='token_symbol',
            field=models.CharField(default='', max_length=50),
        ),
    ]
